//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferenceRoomAddin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entry
    {
        public int id { get; set; }
        public int start_time { get; set; }
        public int end_time { get; set; }
        public int entry_type { get; set; }
        public Nullable<int> repeat_id { get; set; }
        public int room_id { get; set; }
        public System.DateTime timestamp { get; set; }
        public string create_by { get; set; }
        public string modified_by { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public string description { get; set; }
        public byte status { get; set; }
        public Nullable<int> reminded { get; set; }
        public Nullable<int> info_time { get; set; }
        public string info_user { get; set; }
        public string info_text { get; set; }
        public string ical_uid { get; set; }
        public short ical_sequence { get; set; }
        public string ical_recur_id { get; set; }
        public string coffee { get; set; }
        public Nullable<bool> food_needed { get; set; }
        public string catering { get; set; }
        public string requestor { get; set; }
        public Nullable<int> room_layout_id { get; set; }
    
        public virtual Repeat Repeat { get; set; }
        public virtual Room Room { get; set; }
        public virtual RoomLayout RoomLayout { get; set; }
    }
}
