//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferenceRoomAddin.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MRBSEntities : DbContext
    {
        public MRBSEntities()
            : base("name=MRBSEntities")
        {
        }

        public MRBSEntities(string connectionString) : base(connectionString) { }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Entry> Entries { get; set; }
        public virtual DbSet<Repeat> Repeats { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<RoomLayout> RoomLayouts { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
