//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferenceRoomAddin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.Entries = new HashSet<Entry>();
            this.Repeats = new HashSet<Repeat>();
        }
    
        public int id { get; set; }
        public bool disabled { get; set; }
        public int area_id { get; set; }
        public string room_name { get; set; }
        public string sort_key { get; set; }
        public string description { get; set; }
        public int capacity { get; set; }
        public string room_admin_email { get; set; }
        public string custom_html { get; set; }
        public string location { get; set; }
        public string technology { get; set; }
    
        public virtual Area Area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entry> Entries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Repeat> Repeats { get; set; }
    }
}
