//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferenceRoomAddin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomLayout
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomLayout()
        {
            this.Entry = new HashSet<Entry>();
            this.Repeat = new HashSet<Repeat>();
        }
    
        public int id { get; set; }
        public int room_id { get; set; }
        public string layout_name { get; set; }
        public string img_relative_url { get; set; }
        public string thumb_img_relative_url { get; set; }
        public string avail_chairs { get; set; }
        public string avail_tables { get; set; }
        public int sort_key { get; set; }
        public bool is_active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entry> Entry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Repeat> Repeat { get; set; }
    }
}
